import type { Lesson } from '../types'

// Adapted from the supplied rails-asset-pipelines.pdf; source links retained below.
export const railsAssetPipelines: Lesson = {
  slug: 'rails-asset-pipelines',
  title: 'Rails Asset Pipelines',
  tagline: 'A beginner’s guide to Sprockets and Propshaft in development and production.',
  intro:
    'An asset pipeline manages the files a browser downloads: CSS, JavaScript, images, and fonts. This guide follows those files through Sprockets and Propshaft, from editing locally to preparing them for visitors.',
  minutes: 9,
  sections: [
    {
      heading: 'The terminology',
      blocks: [
        {
          kind: 'p',
          text: '**Sprockets** and **Propshaft** are two implementations of the Rails asset pipeline. Rails 8 made Propshaft the default for new applications. Existing applications can still use Sprockets. The Propshaft sections here follow the default Rails 8 approach: plain CSS and JavaScript with import maps, without a frontend compilation or bundling step.',
        },
      ],
    },
    {
      heading: 'What both systems do',
      blocks: [
        {
          kind: 'p',
          text: 'Both systems find assets in configured directories and let your views reference them through Rails helpers. For example, a view can ask for an image by its original filename:',
        },
        { kind: 'code', lang: 'erb', code: '<%= image_tag "logo.png" %>' },
        {
          kind: 'p',
          text: 'For production, the pipeline adds a **fingerprint** to the filename: a hash derived from the file’s content. A name like `logo.png` becomes something like `logo-a1b2c3.png`.',
        },
        {
          kind: 'callout',
          tone: 'note',
          title: 'Why fingerprint filenames?',
          text: 'When the content changes, the fingerprint changes. Browsers can cache the old URL for a long time, while updated pages point to the new URL. Rails helpers resolve the original filename to the prepared asset’s URL.',
        },
      ],
    },
    {
      heading: 'Is there a separate asset server in development?',
      blocks: [
        {
          kind: 'p',
          text: '**No separate server is needed in a standard Rails setup.** Sprockets and Propshaft are Ruby libraries loaded into your Rails application. Starting `bin/rails server` starts the application server, usually Puma, which handles both page requests and asset requests on the same port, typically `localhost:3000`.',
        },
        {
          kind: 'list',
          ordered: true,
          items: [
            'The browser requests a page, such as `http://localhost:3000/posts`. Rails renders HTML containing asset URLs generated by helpers.',
            'The browser reads that HTML and makes additional requests for its stylesheets, scripts, and images under `/assets/...` on the same server.',
            'The configured pipeline handles those asset requests and returns the files. Your own controller actions do not need to serve them.',
          ],
        },
        {
          kind: 'p',
          text: 'Sprockets integrates as a **Rack application** mounted at the asset path. Propshaft installs **Rack middleware** that handles asset requests. Rack is the interface connecting Ruby web servers to application code; middleware is code along the request path that can respond or pass a request onward.',
        },
        {
          kind: 'callout',
          tone: 'note',
          title: '“Asset server” does not mean another process',
          text: 'You may see names such as `Sprockets::Server` or `Propshaft::Server` in documentation. In the Rails integration, these name the Ruby code that responds to asset requests inside the application server. You do not start a separate Sprockets or Propshaft command or give it another port.',
        },
      ],
    },
    {
      heading: 'Sprockets in development',
      blocks: [
        { kind: 'p', text: 'Start Rails, typically with:' },
        { kind: 'code', lang: 'sh', code: 'bin/rails server' },
        {
          kind: 'p',
          text: 'When the browser requests an asset, Sprockets processes it on demand. It can combine files using directives such as `//= require`. With the appropriate processors installed, it can also convert Sass into CSS or CoffeeScript into JavaScript.',
        },
        {
          kind: 'list',
          items: [
            'Sprockets caches processed results and rebuilds affected assets when their source files change.',
            'The normal workflow is edit, save, then refresh the browser. You generally do not run `assets:precompile` locally.',
            'Depending on the Sprockets version and debug settings, development assets may be served separately to make debugging easier.',
          ],
        },
      ],
    },
    {
      heading: 'Sprockets in production',
      blocks: [
        { kind: 'p', text: 'During the build or deployment, run:' },
        {
          kind: 'code',
          lang: 'sh',
          code: 'RAILS_ENV=production bin/rails assets:precompile',
        },
        {
          kind: 'list',
          ordered: true,
          items: [
            'Sprockets processes the assets selected by the application’s manifest and precompile configuration.',
            'It converts supported source formats, combines files as instructed, and minifies them if compressors are configured.',
            'It writes fingerprinted output into `public/assets` and generates a manifest mapping original names to generated filenames.',
            'Rails helpers use that mapping to generate the correct asset URLs.',
          ],
        },
        {
          kind: 'p',
          text: 'A static file server, Rails’ configured static serving, or a CDN delivers the prepared files. Normal production setups prepare assets before deployment, rather than compiling them for each visitor.',
        },
      ],
    },
    {
      heading: 'Propshaft in development',
      blocks: [
        {
          kind: 'p',
          text: 'Follow a single stylesheet, `app/assets/stylesheets/application.css`, from your editor to the browser. It contains ordinary CSS that the browser already understands.',
        },
        {
          kind: 'p',
          text: '**Start the application.** Run `bin/rails server`. Propshaft’s asset handler runs inside the Rails server, so page requests and stylesheet requests use the same port.',
        },
        {
          kind: 'p',
          text: '**Reference the stylesheet.** Your layout uses a Rails helper to include it:',
        },
        {
          kind: 'code',
          lang: 'erb',
          code: '<%= stylesheet_link_tag "application" %>',
        },
        {
          kind: 'p',
          text: '**Resolve the file.** When Rails renders the page, the helper asks Propshaft for `application.css`. This is its **logical name**, relative to an asset directory. Propshaft searches its **load path**, the directories registered in `config.assets.paths`, and finds the file in `app/assets/stylesheets`.',
        },
        {
          kind: 'p',
          text: '**Generate the URL.** Propshaft adds a fingerprint based on the asset’s content, producing a URL such as `/assets/application-a1b2c3.css`. Rails puts that URL in the page’s stylesheet link. Fingerprints are used in development too; you keep editing the original `application.css` file.',
        },
        {
          kind: 'p',
          text: '**Find the requested stylesheet.** The browser requests `/assets/application-a1b2c3.css` from Rails. Propshaft separates the fingerprint from the filename to recover `application.css`, finds that file on its load path, and checks that the fingerprint matches the file’s current version. The fingerprint identifies the version; the original filename identifies the file.',
        },
        {
          kind: 'p',
          text: '**Serve the CSS.** Propshaft returns the stylesheet’s contents. If `application.css` contains a `url(...)` pointing to an image or font managed by Propshaft, it updates that URL to include the referenced asset’s fingerprint before sending the CSS. Ordinary style rules remain as written. This happens on demand, without `assets:precompile` or a generated copy in `public/assets`.',
        },
        {
          kind: 'p',
          text: '**Reuse the work.** As Propshaft finds the stylesheet, calculates its fingerprint, and prepares its CSS, it keeps those results in the Rails server process’s memory. This is Propshaft’s cache: it avoids repeating that work for unchanged files. Separately, the browser can cache the CSS it receives under its fingerprinted URL.',
        },
        {
          kind: 'p',
          text: '**Edit and refresh.** After you save a change to `application.css`, reload the page. Propshaft checks for asset changes before requests and clears its in-memory cache when changes are detected. It then calculates a fresh fingerprint, and the helper puts the updated URL in the page. That new URL tells the browser to fetch the changed CSS instead of reusing its cached version. You normally do not restart Rails; Propshaft does not refresh the browser tab automatically.',
        },
        {
          kind: 'p',
          text: '**Load JavaScript with import maps.** JavaScript follows the same asset-serving path, with an extra piece that tells the browser which files to request. An **import map** connects module names to URLs. Rails defines these entries, called pins, in `config/importmap.rb`; the default "application" pin refers to `app/javascript/application.js`.',
        },
        {
          kind: 'p',
          text: '**Put the map in the page.** The layout’s `javascript_importmap_tags` helper uses Propshaft to resolve local JavaScript files to fingerprinted URLs. It embeds the import map in the HTML and tells the browser to import "application".',
        },
        {
          kind: 'p',
          text: '**Let the browser load the modules.** The browser looks up "application" in that map and requests its JavaScript from Rails. As it encounters further named imports, it uses the map to find those modules too. Propshaft serves the files individually, and the browser runs them. Your JavaScript stays in separate files throughout this process.',
        },
        {
          kind: 'p',
          text: '**Refresh after JavaScript edits.** Save your changes and reload the page. Rails renders the import map with updated asset URLs, and the browser fetches the changed modules. Import maps handle JavaScript names and URLs; Propshaft handles finding, fingerprinting, and serving the local files. The stylesheet continues to load through its stylesheet helper.',
        },
      ],
    },
    {
      heading: 'Propshaft in production',
      blocks: [
        { kind: 'p', text: 'When preparing the application for deployment, run:' },
        {
          kind: 'code',
          lang: 'sh',
          code: 'RAILS_ENV=production bin/rails assets:precompile',
        },
        {
          kind: 'list',
          ordered: true,
          items: [
            'Propshaft copies assets from its configured paths, excluding explicitly excluded directories, into `public/assets`.',
            'It fingerprints the files, updates supported asset references, and writes `public/assets/.manifest.json`.',
            'When Rails renders a page, the stylesheet helper uses the manifest to generate the CSS URL. The import-map helper uses it to resolve local JavaScript pins to their prepared URLs.',
            'The browser loads the stylesheet and uses the import map to request individual JavaScript modules. A static file server, Rails’ configured static serving, or a CDN delivers those prepared files.',
          ],
        },
        {
          kind: 'p',
          text: 'Rails 8’s **no-build** approach still includes this deployment preparation. Here, **precompile** means preparing asset files and their fingerprinted names; your CSS and JavaScript are already browser-ready. Import maps continue to connect JavaScript names to URLs in production, just as in development.',
        },
      ],
    },
  ],
  takeaways: [
    'In standard development setups, Sprockets or Propshaft serves assets inside the Rails application server, using the same port.',
    'Both pipelines locate assets and prepare fingerprinted filenames so browsers can cache files while pages reference updated versions.',
    'Sprockets can process and combine assets, with compilation and compression depending on the installed processors and configuration.',
    'The default Rails 8 approach pairs Propshaft with import maps: Propshaft manages local asset files and URLs, while import maps let the browser load JavaScript modules by name.',
    'Development usually means edit, save, and refresh. Production uses `assets:precompile` to prepare assets before visitors request them.',
  ],
  goDeeper: [
    {
      label: 'Rails 8 announcement: Propshaft becomes the default',
      url: 'https://rubyonrails.org/2024/11/7/rails-8-no-paas-required',
    },
    {
      label: 'Rails Guides: The Asset Pipeline',
      url: 'https://guides.rubyonrails.org/asset_pipeline.html',
    },
    { label: 'Sprockets documentation', url: 'https://github.com/rails/sprockets' },
    {
      label: 'Rails 7.2 Guides: The Asset Pipeline (Sprockets)',
      url: 'https://guides.rubyonrails.org/v7.2/asset_pipeline.html',
    },
    { label: 'Propshaft documentation', url: 'https://github.com/rails/propshaft' },
    {
      label: 'Propshaft development asset request handler',
      url: 'https://github.com/rails/propshaft/blob/main/lib/propshaft/server.rb',
    },
    {
      label: 'Propshaft development URL resolution',
      url: 'https://github.com/rails/propshaft/blob/main/lib/propshaft/resolver/dynamic.rb',
    },
    {
      label: 'Sprockets Rails integration: mounting the asset handler',
      url: 'https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb',
    },
    {
      label: 'Propshaft Rails integration: installing asset middleware',
      url: 'https://github.com/rails/propshaft/blob/main/lib/propshaft/railtie.rb',
    },
    {
      label: 'Import maps for Rails',
      url: 'https://github.com/rails/importmap-rails',
    },
  ],
}
